name: New gitea release
run-name: Create a new gitea release on tag push
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create a new release
    runs-on: services1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47

      - name: List changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "List all the files that have changed: $ALL_CHANGED_FILES"

#      - name: Create gitea release
#        uses: https://gitea.com/actions/gitea-release-action@v1
#        with:
#          files: |-
#            Dockerfile
#            entrypoint.sh
#          body: |
#            Changes:
#            ${{ steps.changed-files.outputs.all_changed_files }}
