name: New gitea release
run-name: Create a new gitea release when a tag is pushed
on:
  push:
    branches:
      - "**"

jobs:
  release:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: 
